### PR TITLE
Tmp/single line comments removal

### PR DESCRIPTION
**Pull request by ByunghunLee**
Single line comments in the DBC files lead to parsing error.
So I added lines to remove single line comments by using regular expression from _dbcppp_NetworkLoadDBCFromFile_ and _fromDBC_ methods in the DBCAST2Network.cpp file.
constexpr auto single_comment_regular_expr = "^\\s*//.*?$";

I also added test case and a dbc file including single line comments.

### CODE REVIEW

**Comment by xR3b0rn** [comment]
Thank you for your effort.
1. If you create a pull request, please try to keep the tab-convetion (the project uses 4 spaces instead of \t), because like it is now, git is not able to create a meaningful diff, what makes accepting a pull request much harder.
Could you apply that on your pull request? Maybe the best way to go for that pull request is to refork and apply your changes on the new fork.
2. I could not find anything about //-comments in the description of the grammar. Could you explain in more detail where you got that information from?

**Comment by ByunghunLee** [comment]
Hello

The single line comments are found in some DBC files, which seem like
generated by machines.
Even though the single line comments are not defined in the grammar, vector
tools allow only single line comments (Multi line comments are not allowed).
So, I thought that pre-processing the dbcs is better than changing the
grammar part.

I will create a new pull request after changing wrong tab-conventions.

Thanks.

Regards




2020년 9월 16일 (수) 오후 2:17, xR3b0rn <notifications@github.com>님이 작성:

**Comment by xR3b0rn** [comment]
After thinking a while, I started to like the idea of preprocessing the DBC file, since comments are afaik not part of the actual grammar.

But I think there could be some problems when it comes to preprocess a `_char_string`. I think you should add this case to your test and then try to make it work.
The easiest way to add a construct using `_char_string` to your DBC is to add a `CM_`:
`CM_ "Test comment with // in it"`

**Comment by xR3b0rn** [comment]
`make RunTests` on your branch fails, you can check it here: https://travis-ci.org/github/xR3b0rn/dbcppp/pull_requests

**Comment by xR3b0rn** [comment]
As the pull request is right now I can not merge it, since I do not want to add the iconv library. I am also not sure if the iconv library will compile on Windows.

**Comment by ByunghunLee** [comment]
The iconv lib was added for test purpose. I found an alternative way.
I removed iconv from third_party directory.

**Comment by xR3b0rn** [comment]
Looks great. Just one more thing: Is it possible to use `std::regex` instead of `boost::regex`, or do you have any special reason for using `boost` there?

If you can adjust that, I will merge it PR.

**Comment by ByunghunLee** [comment]
No, there is any special reason.
I will push it with `std::regex`.

**Comment by ByunghunLee** [comment]
Hello xR3b0rn,

 

Std:regex has an issue on g++ 9.xx.

 

The regular expression works fine with std::regex and boost::regex in VS2017. 

However, it does not detect the single line comments in g++ 9.xx.

 

Can we back to the version of using boost::regex?

Please let me know.

Thank you.

**Comment by xR3b0rn** [comment]
I rolled back to the last working commit. I think there should be a way to make it work with gcc. Can you try to make it work with gcc? I want to have as less dependencies on boost as possible.

I think then you have to create a new PR.

**Comment by ByunghunLee** [comment]
Sure.

I understood.

 

Thanks.

**Pull request merged**
